version: '3' 
services: 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
      args: 
        USER_UID: 10000 
        USER_GID: 10000 
    init: true 
    volumes: 
      - ..:/workspace:cached 
    command: sleep infinity 
    user: vscode 
  azurite: 
    image: mcr.microsoft.com/azure-storage/azurite:latest 
    ports: 
      - '10000:10000' 
      - '10001:10001' 
      - '10002:10002' 